title: Namplifier
author: Michał Kalbarczyk
description: VST
url: "https://namplifier.fazibear.me"

permalink: /v/:title/

collections:
  versions:
    output: false

# plugins:
#   - jekyll-feed
#   - jekyll-sitemap
